apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: alejozpt97/aztro-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
              secretKeyRef:
                name: secrets
                key: DefaultConnection
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_KEY
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_ISSUER
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_AUDIENCE