using Api.DataContext;
using Api.Models;
using Microsoft.EntityFrameworkCore;

namespace Api.Seeders
{
    public class DestinoSeeder : ISeeder
    {
        public int Order => 2; // Después de Continentes

        public async Task SeedAsync(AmadeusContext context)
        {
            if (await context.Destinos.AnyAsync())
            {
                Console.WriteLine("⚠️  Los destinos ya están poblados. Saltando seeder...");
                return;
            }

            Console.WriteLine("🌎 Poblando tabla de Destinos...");

            // Obtener los IDs de los continentes según el orden de inserción
            var asia = await context.Continentes.FirstOrDefaultAsync(c => c.Nombre == "Asia");
            var america = await context.Continentes.FirstOrDefaultAsync(c => c.Nombre == "America");
            var europa = await context.Continentes.FirstOrDefaultAsync(c => c.Nombre == "Europa");

            var destinos = new List<Destino>
            {
                new Destino { Nombre = "Playa del Carmen, Mexico", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "México", Idioma = "español", LugarImperdible = "Chichén-Itzá", ComidaTipica = "Salbutes", ImgUrl = "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSsEgGDtay7yynbtJCdRRvuLW0dWTzG3_BDf36Vo0flnkq7E_BJpr3-EclLGqYfPhIn-REwJqGs0lcfgpU6M34pYibADP7HTCHvX9jwZA" },
                new Destino { Nombre = "Santorini, Grecia", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Grecia", Idioma = "Griego", LugarImperdible = "Oia", ComidaTipica = "Moussaka", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSKEchVmyIPbv1XBHQVjbCGSu7ELlk46OgcW6MoKl6upCUiKu7wUP0K0E-mRbjo_m24dJMpjn5hbxr_SWgU5-Irm43Ay4cHtFjA_AOd-w" },
                new Destino { Nombre = "Cartagena, Colombia", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Colombia", Idioma = "Español", LugarImperdible = "Ciudad Amurallada", ComidaTipica = "Cazuela de Mariscos", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipMVfyWlbwj-OyndRaLB8OcBQ3qFQffDq343NUNj=w540-h312-n-k-no" },
                new Destino { Nombre = "Barcelona, España", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "España", Idioma = "Español", LugarImperdible = "Sagrada Familia", ComidaTipica = "Paella", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipOxwFRsHTWMWABPquEmNX4bIqjJk8Gu5YYoeFvs=w540-h312-n-k-no" },
                new Destino { Nombre = "Rio de Janeiro, Brasil", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Brasil", Idioma = "Portugués", LugarImperdible = "Cristo Redentor", ComidaTipica = "Feijoada", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipPUTncdgQzogJ1bTDMPJJX3nqQjs0FZ4iDpf-he=w540-h312-n-k-no" },
                new Destino { Nombre = "Lisboa, Portugal", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Portugal", Idioma = "Portugués", LugarImperdible = "Torre de Belém", ComidaTipica = "Bacalhau à Brás", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipNPJSyPRk-i6wRJQ3IJwjCxE2qdbGXCFpkXQ_LR=w540-h312-n-k-no" },
                new Destino { Nombre = "Bariloche, Argentina", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Argentina", Idioma = "Español", LugarImperdible = "Cerro Catedral", ComidaTipica = "Asado", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQ-SfIII1xLSAS3oV3zrIJG83_dEcpy0Lg5VfycEokHpeYo0xeI7rGambr0tYacAtaUKn6pR5NrEZ4RQmPmyUhkyG13FPrmAfaCDY6wKQ" },
                new Destino { Nombre = "Interlaken, Suiza", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Suiza", Idioma = "Alemán", LugarImperdible = "Jungfraujoch", ComidaTipica = "Fondue", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipMC6smIuDIlHhsE4OWqUZxEn3t8uqgI_aSlFmaA=w540-h312-n-k-no" },
                new Destino { Nombre = "Cusco, Perú", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Perú", Idioma = "Español", LugarImperdible = "Machu Picchu", ComidaTipica = "Ceviche", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipORjUq02fgtogOziVA5Qe5JxJGHlRatzuhMUhf8=w540-h312-n-k-no" },
                new Destino { Nombre = "Granada, España", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "España", Idioma = "Español", LugarImperdible = "Alhambra", ComidaTipica = "Tortilla Española", ImgUrl = "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcRxOTQBjLt3480QFzkSlhnnZ0mQVZh4VVnDbBXXlvwv-ya_zuxGyBaKYYBzqp8r2MwBsVRnZl9a3ZJE9GST0V-vExD6FEYqBfT_7LLzBg" },
                new Destino { Nombre = "Banff, Canadá", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Canadá", Idioma = "Inglés", LugarImperdible = "Lago Moraine", ComidaTipica = "Poutine", ImgUrl = "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS5i1pBNjrxyDIxWtAVJW_lkrL1AV0NUkXfsAQxDMgrCyCrArqVxTBc7vms74IlKRt2pjDSqpkLtK3dp7IBabCWuJSncQ_NMJq18K0oug" },
                new Destino { Nombre = "Zermatt, Suiza", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Suiza", Idioma = "Alemán", LugarImperdible = "Matterhorn", ComidaTipica = "Rösti", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSAQcCDSb6m6eo3VJ1mZ8zlT4J3poq2-v3PM0Ph6atAFrnMKHXTClkZLKrkx0vRMPPfGJlApHInz4J3vpZePZ9csZB8K38Sgr-09Hrneg" },
                new Destino { Nombre = "Nueva York, EE.UU", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "EE.UU", Idioma = "Inglés", LugarImperdible = "Central Park", ComidaTipica = "Hamburguesa", ImgUrl = "https://lh3.googleusercontent.com/proxy/g-ljxmC9hqYpgbNRM2dhT4x30UsLIeylGkNR8j7xU75F3uXUHTB-hNcdjNy_H5_ZxgnbUxNUvne8TOZBcYT-BwoIQZgXwXlkyciXBHBPkNH2SavG7WhWDqT383O5PPPhie3Pw0fSRriv3TF8TEb8cu7JuH5-_Q=w540-h312-n-k-no" },
                new Destino { Nombre = "París, Francia", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Francia", Idioma = "Francés", LugarImperdible = "Torre Eiffel", ComidaTipica = "Croissant", ImgUrl = "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQB19lTbuMXK3ICGgIQium_8s9s3aWQyeCqY6_k4EHJE8Bqfwsj_bHFtzpOInjAbBrVo98xmieHU1-pRhEDJ941EUyPRa7BpiF1V5o9KA" },
                new Destino { Nombre = "Miami, EE.UU", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "EE.UU", Idioma = "Inglés", LugarImperdible = "Ocean Drive", ComidaTipica = "Cubano", ImgUrl = "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcShxWawBkoL_1-TwGmiYpGoK7TWnMNIqOXjyPTWeMewhsGd1MZAqBByntjcu_1o99Qeh55FPRs_U8qNuJr9qg_9mLT48KPzMjYGrUJxpg" },
                new Destino { Nombre = "Viena, Austria", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Austria", Idioma = "Alemán", LugarImperdible = "Palacio de Schönbrunn", ComidaTipica = "Wiener Schnitzel", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQhmmjDULK_wpRBu1pTjscz0_jzZNayOww794qmfUoBOenvO_tJ03meRDfBWULqH1rf5pIN-bw7pOT90T88wMzE621kDAhJTyGWhC7X7g" },
                new Destino { Nombre = "Toronto, Canadá", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Canadá", Idioma = "Inglés", LugarImperdible = "CN Tower", ComidaTipica = "Poutine", ImgUrl = "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSW9ckAy6THoZo16osm6gFx8FTw_eEwUwBQsPyJP8i9-tS0XcRF9Gjiur9Jr1MKjHIowILKm3Dg3Z0qt-ashs7uvQJTkJ4skbX2rIxXHA" },
                new Destino { Nombre = "Berlín, Alemania", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Alemania", Idioma = "Alemán", LugarImperdible = "Puerta de Brandeburgo", ComidaTipica = "Currywurst", ImgUrl = "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTIfYrJDD7_H9dZcmHZeKr9TmEAQ4KbxOO4b67XIfn0mpkzPwqmJvBSWxDX_PcOwi3BByZY-wrbGfQJp3lcwdgwiwv6JXaYqO7IEE90kQ" },
                new Destino { Nombre = "Tulum, México", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "México", Idioma = "Español", LugarImperdible = "Ruinas de Tulum", ComidaTipica = "Tacos", ImgUrl = "https://lavidasondosviajes.com/wp-content/uploads/2022/06/ruinas-que-ver-en-tulum.jpg" },
                new Destino { Nombre = "Ibiza, España", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "España", Idioma = "Español", LugarImperdible = "Playa de Ses Illetes", ComidaTipica = "Paella", ImgUrl = "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQ25B41WBP9PXz5J-Kg2LM_4H1x_EfdtLlZ30eH9NTkBRl-e1tmt2uCb95nRfoOGRx46b4dAaquteRwnEsuxznkzp__o638eoKafYjCKQ" },
                new Destino { Nombre = "Ushuaia, Argentina", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Argentina", Idioma = "Español", LugarImperdible = "Canal Beagle", ComidaTipica = "Asado", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcS3ZsFFeuBcky5BXnAv9mzhfZpckqXbQeUibmvY7SmFLqMN6lkkPbcm2TIsyVM0EDsLTsuFiXXrIX2_hELULGdxGBuZMlawKTEFCcT1JA" },
                new Destino { Nombre = "Reykjavik, Islandia", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Islandia", Idioma = "Islandés", LugarImperdible = "Blue Lagoon", ComidaTipica = "Skyr", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipOd0uslkh05Ey3auyorQ9kYVGA3dRhyIthKVcKy=w540-h312-n-k-no" },
                new Destino { Nombre = "Punta Cana, República Dominicana", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "República Dominicana", Idioma = "Español", LugarImperdible = "Playa Bávaro", ComidaTipica = "Mangú", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSoeSjS2oex8LXHfqhd7M980AKuGvblppPnTJyhGHIcQDEWN_Dy7c78v9_aiSralykZiaQJllvJssKa6SVO96jM5RiFSjdQzgzmkdoh6g" },
                new Destino { Nombre = "Algarve, Portugal", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Portugal", Idioma = "Portugués", LugarImperdible = "Praia da Marinha", ComidaTipica = "Cataplana", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipMeTMP4wkVkLLhbKbwUSL0116sXNlp9QywbNLcd=w540-h312-n-k-no" },
                new Destino { Nombre = "Chicago, EE.UU", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "EE.UU", Idioma = "Inglés", LugarImperdible = "Millennium Park", ComidaTipica = "Hot Dog", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipNMCexgTHrhXahYlqYPCnn8tABv5ZS3NOXVi3b4=w540-h312-n-k-no" },
                new Destino { Nombre = "Londres, Reino Unido", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Reino Unido", Idioma = "Inglés", LugarImperdible = "Big Ben", ComidaTipica = "Fish and Chips", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRfy0GJeSvOlk4DCD5F_KBpRmVv1zMAjd4Q3jxsRwasl5N3KplKt3RoJWUMrNV6Wd6E7oqYfPGRFZPvc66qqjUqlg8LD73_dEIJRNzTqg" },
                new Destino { Nombre = "San Juan, Puerto Rico", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Puerto Rico", Idioma = "Español", LugarImperdible = "Viejo San Juan", ComidaTipica = "Mofongo", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTM3yildmlADM2AbK61asNKPTgqZiYCG4zPnyuBTOF5UqtQ5S_Gl1ZN-GPW49u9w15jjGNMLCBigbpzztwY-W5PxSlkQFhLHN8d4Cqgsg" },
                new Destino { Nombre = "Niza, Francia", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Francia", Idioma = "Francés", LugarImperdible = "Paseo de los Ingleses", ComidaTipica = "Ratatouille", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcT4PkkEFmk1DoQUKoAPN5uK2ZxwCM0HZ-HEDuoTq3sdFK0oAuTUyLm7mmwRo1ysqgr97CTceNK9QUUYLn80PrrjCXRyf81JV5HYudCOzw" },
                new Destino { Nombre = "Machu Picchu, Perú", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "Perú", Idioma = "Español", LugarImperdible = "Machu Picchu", ComidaTipica = "Ceviche", ImgUrl = "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQT8tfTOX2rjqW3LMhTELr_7BRIJq8sckiw7BA0UL4Zb7P_lcESksxQU0Kt0mebaK6qzjy0HQ_G_dQaFVzoR9wuM7t0pIu6REhO1_dHBw" },
                new Destino { Nombre = "Chamonix, Francia", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Francia", Idioma = "Francés", LugarImperdible = "Mont Blanc", ComidaTipica = "Fondue", ImgUrl = "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcTZ1HbSdRjQyBqQ_uWmhwwUA-3JpvnkHCVrQ2RvYZOAo5BvtEriEaSg_oiiL9buc5p4QoN1YwM6MAC4BIXSqjitaFrW9E3AukjNP_CDGw" },
                new Destino { Nombre = "Los Ángeles, EE.UU", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "EE.UU", Idioma = "Inglés", LugarImperdible = "Hollywood", ComidaTipica = "Hamburguesa", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRNmhjFYQEGxB9QMDa2x-_JuVWEiy1SoC4JWitgfe6jQxXUB1KKgxYuZnjK1pKEC351O7bAJvI8oryJ5dotu-dCCOAFfbeOS0bmZu7cNw" },
                new Destino { Nombre = "Roma, Italia", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Italia", Idioma = "Italiano", LugarImperdible = "Coliseo", ComidaTipica = "Pizza", ImgUrl = "https://lh5.googleusercontent.com/proxy/Yzdb0Ml3JUhHIDZNG7ZbDXHechmZEMx1qZlClkzqfXy4bg7GiSSxU_OqP9omjbjK5VrP7KlHjExf62KsCzGl33Ju_7yQq7eBXWdCIMGVlTyGx1D7LR6lL0wBaif8RbiCYmQvMg4xpLY31PfgaqVhvGj24I_Qpw=w540-h312-n-k-no" },
                new Destino { Nombre = "Honolulu, Hawái", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "EE.UU", Idioma = "Inglés", LugarImperdible = "Waikiki", ComidaTipica = "Poke", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcS770_NITGECjC-qrIDg3B3T6xG4PquUJSSIHTZahPn6P_q_M5Fl-X8Bf2CACF6eZcFqbvjXm7JatvY4imUau1yTUQrHXzY4cV48nN_aQ" },
                new Destino { Nombre = "Malta", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Malta", Idioma = "Maltés", LugarImperdible = "La Valeta", ComidaTipica = "Pastizzi", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRDWSP6xOunmLK_KL3RrCM6nfHSjdg0V4VgBxNLTcNKwubNZIV4m6Zn44a_0t9JzmEEvSx175nAbtJjsbyf5uhWdw8E1EGRspDW67EOMg" },
                new Destino { Nombre = "Aspen, EE.UU", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "EE.UU", Idioma = "Inglés", LugarImperdible = "Maroon Bells", ComidaTipica = "Hamburguesa", ImgUrl = "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR0Lj48jrr1E690626PW3U3qSi6n2dgTlSk0BNXb3MheFId7XcPX44CdE9a07j7E_u9lKvi--yQMTfEk33WipVyWV4ojD3hW0uGoqaA_w" },
                new Destino { Nombre = "Innsbruck, Austria", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "Austria", Idioma = "Alemán", LugarImperdible = "Tejado de Oro", ComidaTipica = "Wiener Schnitzel", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSzy7HLAM-zxvpiEvSV6T4ITO8h9KRj9P7Exhg28AcSYgkHpIK_1zKzg6PhoTneIUBdEtWivfw3PYGNcX8Kh3euTuWcICxaYOUlXkiMBA" },
                new Destino { Nombre = "Ciudad de México, México", ContinentesId = america?.Id, CreatedAt = DateTime.Now, Pais = "México", Idioma = "Español", LugarImperdible = "Zócalo", ComidaTipica = "Tacos", ImgUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcRkqHlAgGAAIXOIO02KVBc0Q9tGSUACQlUmvIrcqN9Ukg8RFxXubFKx0IAmyBsHdQ24rlbC4zIvIVh0o6f1-AKDjlnLmvp6rficC1BZRw" },
                new Destino { Nombre = "Madrid, España", ContinentesId = europa?.Id, CreatedAt = DateTime.Now, Pais = "España", Idioma = "Español", LugarImperdible = "Parque del Retiro", ComidaTipica = "Cocido Madrileño", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipPp7gG6UeQm7kyfY5d_KCZbDZnKjsFGMTpUH8YQ=w540-h312-n-k-no" },
                new Destino { Nombre = "Bora Bora, Polinesia Francesa", ContinentesId = asia?.Id, CreatedAt = DateTime.Now, Pais = "Polinesia Francesa", Idioma = "Francés", LugarImperdible = "Monte Otemanu", ComidaTipica = "Poisson Cru", ImgUrl = "https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcR8FpQa5S2XLD5B_v-lLquzTFpzP5KADiZTjL1DAuLgX__enFb89uGALIovy4q8HXPohX6aiAPJz_pTcqwno31RIV58XsBQJyzm17p-1w" },
                new Destino { Nombre = "Dubái, Emiratos Árabes", ContinentesId = asia?.Id, CreatedAt = DateTime.Now, Pais = "Emiratos Árabes", Idioma = "Árabe", LugarImperdible = "Burj Khalifa", ComidaTipica = "Shawarma", ImgUrl = "https://lh5.googleusercontent.com/p/AF1QipM3Su1i0T610BB_q7wHixPLDVhMPdMoMHU21eHV=w540-h312-n-k-no" }
            };

            await context.Destinos.AddRangeAsync(destinos);
            await context.SaveChangesAsync();
            Console.WriteLine($"✅ Se insertaron {destinos.Count} destinos correctamente");
        }
    }
}