name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy: 
    if: > 
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/aztro-api:latest \
            ./api

      - name: Build and push frontend image
        run: |
            docker buildx build \
                --platform linux/amd64 \
                --push \
                --build-arg VITE_API_URL=https://${{ secrets.API_APP_NAME }}.azurewebsites.net \
                -t ${{ secrets.DOCKER_USERNAME }}/aztro-web:latest \
                ./web

      - name: Deploy to server
        run: |
          echo "🚀 Deploying to Azure or other service..."